### PR TITLE
Line Disconnection bug in _BackendAction fix

### PR DESCRIPTION
**Pull request by anton-musrevinu**
Due to an indexing error int the update_state method of the _BackendAction lines with idx 0 and -1(and sometimes 1) are sometimes disconnected.

A script to reproduce the bug is given below. Here a seed was found that produces the bug after a few steps.
[reproduce_stepping_bug.zip](https://github.com/rte-france/Grid2Op/files/8698834/reproduce_stepping_bug.zip)

### CODE REVIEW

**Comment by BDonnot** [comment]
Hello,

Thanks a lot for this pull request and nice catch of this bug !

I will have a look at the code you joined and try to submit you a PR with the proper test. Once merged into your code, I will merge it here.

I think it will be better that there is a identified test before merging (to prevent any reappearing of this bug)

Benjamin

**Comment by anton-musrevinu** [comment]
Hi Benjamin,

**Comment by BDonnot** [comment]
Hi :-)

Can you merge the pull request I made here: https://github.com/anton-musrevinu/Grid2Op/pull/1

Once done, I will merge this PR to the main repo.

Thanks :-)

**Comment by anton-musrevinu** [comment]
Sounds good, I just merged the tests :)

**Review by BDonnot — APPROVED** [review]
Thanks for solving this tricky issue !

**Pull request merged**
