### PR TITLE
Added proper default value to 'make' that create the envs

### PR DESCRIPTION
**Pull request by benedikt-schesch**
Adds a proper default value to the creation of the environment. Also makes the type hints correct.

### CODE REVIEW

**Comment by benedikt-schesch** [comment]
Resolves issue #522

**Comment by BDonnot** [comment]
Hello,

I disabled the default environment (for clarity) in previous grid2op release : I don't think it's a good idea to have something by default, especially this environment (`l2rpn_case14_sandbox` would be a much better but lacking lots of features)

I think the best approach would be to force the first argument, for example with removing the `=None` (this is definitely what I should have done)

Thanks for this PR but as is I am not sure i will merge it (though i'm open for discussion on the default argument to the dataset_path of course and I can change my mind about it)

**Comment by benedikt-schesch** [comment]
@BDonnot I think you are right, there should be no default value. I changed the typing and the notebook to reflect this correctly.

**Comment by BDonnot** [comment]
can you make it to dev_1.9.6 now please ? I made a realease to fix some bugs (including the high priority one you spotted) yesterday.
Thanks :-)

**Comment by benedikt-schesch** [comment]
@BDonnot There you go

**Pull request closed without merging**
